a few bug fixes applied.
LottieRugg/portfolio pull request #3
Opened 2022-03-15 14:55 UTC by LottieRugg

2022-03-15 14:57 UTC, LottieRugg commented
Still buggin on the nav bar and the "let's work together" button on on very small screen sizes.

2022-03-15 17:22 UTC, haefnir requested changes
line 147 and 150 should probably `target="_blank"` 

add normalize.css to your project

let me know when this is pushed and will check again :)

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>      width: 100%;
width not needed, default is 100%

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +    color: #214794;
`footer a{` is more specific so this does nothing

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          background-color: #fae3e5;
not needed, already defined on line 108

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>      width: 100%;
not needed, default is 100%

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>      width: 100%;
not needed, default is 100%

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +    flex-direction: row;
not needed, default value

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +    width: 100%;
default value

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>      z-index: 2;
this doesn't seem to be doing anything

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +    color: #214794;
all `<a>` appear to have this styling. Could remove and make general rule
```
a {
    color:#214794;
}
```

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          display: grid;
already set to `display: grid` 
can delete this

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>      }
two rulesets for .my-experience in this block. Consolidate changes and delete one.

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          display: grid;
already set to `display:grid`

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          display: grid;
already set to `display:grid`

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>      padding: 60px 40px;
this is being overriden by next padding instruction

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +   width: auto;
default value

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +        margin: 0;
This does nothing

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          display: grid;
already defined earlier

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          margin:0;
does nothing

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
>          width: 100%;
does nothing

2022-03-15 17:22 UTC, haefnir commented on stylesheet.css
> +        height: auto;
doesn't seem to do anything

2022-03-16 09:26 UTC, LottieRugg commented on stylesheet.css
> +        margin: 0;
I'm going to keep this as it is needed to style for small screen sizes.

2022-03-16 09:29 UTC, LottieRugg commented on stylesheet.css
>          width: 100%;
on v small screen sizes removes the background image

2022-03-16 09:30 UTC, LottieRugg commented on stylesheet.css
> +        height: auto;
stops images stretching out of proportion on small screens

2022-03-16 09:30 UTC, LottieRugg commented
Thank you for your very thorough review Seb!!!👑

2022-03-16 14:19 UTC, haefnir requested changes
scaling issue around viewport width 990px. Fix then push back for review :)

2022-03-16 14:19 UTC, haefnir commented on index.html
>      <title>Portfolio</title>
Would be a good idea to have your name in the title!

2022-03-16 14:19 UTC, haefnir commented on index.html
> +        </a>
inconsistent indentation

2022-03-16 14:19 UTC, haefnir commented on stylesheet.css
>          display: grid;
this repeats. delete. also defined earlier in the style sheet

2022-03-16 14:19 UTC, haefnir commented on stylesheet.css
>          display: grid;
defined earlier in the stylesheet, not needed

2022-03-16 16:04 UTC, haefnir requested changes

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
> +        /* place-self:center; */
delete this if its not going to feature

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
> +        /* margin: auto; */
delete this if its not going to feature

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
> +    } */
delete if not going to feature

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
>  footer{
footer breaks at resolutions with width below 365px, consider adding a conditional rule to the media check

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
>          background-color:#FFFFFF;
this is defined earlier in the stylesheet, so isnt needed

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
> +        padding: 0;
this padding is being overriden in this block. delete

2022-03-16 16:04 UTC, haefnir commented on stylesheet.css
> +		grid-template-columns: 100%;
fix indentation

2022-03-16 16:12 UTC, haefnir approved these changes
Footer works, approved!

2022-03-17 09:34 UTC, merged